### PR TITLE
Release version 2.3.0

### PR DESCRIPTION
**Pull request by y9c**
Could you help release a new minor version to include the update on species file.

- add 3 new species
- fix error of minor species release version
- format code with black formatter

### CODE REVIEW

**Comment by y9c** [comment]
New feature:

- list all available species to be download

**Comment by y9c** [comment]
Bug fix:

https://github.com/openvax/pyensembl/issues/297

**Comment by y9c** [comment]
Support plant and fungi genome. 
Close: https://github.com/openvax/pyensembl/issues/298

**Comment by y9c** [comment]
Merge with:
https://github.com/openvax/pyensembl/pull/293/files

**Comment by iskandr** [comment]
Sorry for the long delay, I just merged the branch which finishes migrating unit tests to pytest, fixed a few misc. bugs (including figuring out correct Ensembl release versions for C. Elegans). 

If merging the new code with this branch is too much work I can take a stab at porting over isolated enhancements like new species.

**Comment by y9c** [comment]
Hi @iskandr, 

I have fixed the conflict with the main branch. Could you provide some suggestion for future edit?

**Comment by iskandr** [comment]
Hey @y9c -- I've been cleaning up the OpenVax tools and hopefully catching some of the features from your PRs in those changes. If there's anything I have missed can you open those up as new issues or smaller scoped PRs?

**Pull request closed without merging**
